#  ____       _   __  __ _           _____
# |  _ \ _ __| |_|  \/  (_)_ __   __|_   _| __ ___  __ _ ___ _   _ _ __ ___  ___
# | |_) | '__| __| |\/| | | '_ \ / _ \| || '__/ _ \/ _` / __| | | | '__/ _ \/ __|
# |  __/| |  | |_| |  | | | | | |  __/| || | |  __/ (_| \__ \ |_| | | |  __/\__ \
# |_|   |_|   \__|_|  |_|_|_| |_|\___||_||_|  \___|\__,_|___/\__,_|_|  \___||___/
#                                                                      by Pretti_

#
# Permissions:
# - prtmt.command        = To be able to access the list of commands with the /mt;
# - prtmt.command.reload = To be able to reload the plugin with the /mt reload;

#
# OPTIONS
#
options:
  # Set the value for the method of removing vanilla drops:
  # - true: Always removed.
  # - false: Never removed.
  remove-vanilla-drops: true

  # Set the amount of treasures that can be triggered at a time.
  treasures-limit: 1
