#  ______           ______                           _____                    _     _ _ _
# (_____ \     _   / _____)          _              (____ \                  | |   (_) (_)_
#  _____) )___| |_| /     _   _  ___| |_  ___  ____  _   \ \ _   _  ____ ____| | _  _| |_| |_ _   _
# |  ____/ ___)  _) |    | | | |/___)  _)/ _ \|    \| |   | | | | |/ ___) _  | || \| | | |  _) | | |
# | |   | |   | |_| \____| |_| |___ | |_| |_| | | | | |__/ /| |_| | |  ( ( | | |_) ) | | | |_| |_| |
# |_|   |_|    \___)______)____(___/ \___)___/|_|_|_|_____/  \____|_|   \_||_|____/|_|_|_|\___)__  |
#                                                                                            (____/
#                                                                                         by Pretti_

#
# Permissions:
# - customdurability.command.customdurability = To be able to access the list of commands with the /cd;
# - customdurability.command.reload           = To be able to reload the plugin with the /cd reload;

#
# OPTIONS
#
options:
  # Set the maximum durability level for server armor.
  max-durability: 35

  # Set the minimum chance of armor damage calculation.
  min-chance: 30.0
