#  ____       _   __  __ _           _____
# |  _ \ _ __| |_|  \/  (_)_ __   __|_   _| __ ___  __ _ ___ _   _ _ __ ___  ___
# | |_) | '__| __| |\/| | | '_ \ / _ \| || '__/ _ \/ _` / __| | | | '__/ _ \/ __|
# |  __/| |  | |_| |  | | | | | |  __/| || | |  __/ (_| \__ \ |_| | | |  __/\__ \
# |_|   |_|   \__|_|  |_|_|_| |_|\___||_||_|  \___|\__,_|___/\__,_|_|  \___||___/
#                                                                      by Pretti_

#
# Permissions:
# - prtmt.command        = To be able to access the list of commands with the /mt;
# - prtmt.command.reload = To be able to reload the plugin with the /mt reload;
# - prtmt.bypass.owner   = Bypass the owner-only option of the crate.

# DEPENDENCIES
dependencies:
  use-server-nbt-api: true # This tells the plugin to use the manually installed NBT API version in the server’s plugins/ folder. Setting it to false forces PrtMineTreasures to use the shaded version. Enable this if your plugin runs on an unsupported server version.

# GENERAL
options:
  treasures-limit: 1              # Maximum number of active treasures
  remove-vanilla-drops: false     # Remove vanilla drops? (true/false)
  drop-to-inventory: true         # Drop items directly into inventory? (true/false)
  discard-excess: true            # Discard excess items? (true/false)

#
# CRATES SETTINGS
# - Inventory name, messages from the boxes can be found in the message file.
#
crates:
  block-type: CHEST     # Type of block used for the crate
  destroy-time: 300     # Time before the crate disappears (seconds)
  owner-only: true      # Only the treasure owner can open it? (true/false) [bypass permission: prtmt.bypass.owner]
  inventory-rows: 3     # Number of inventory rows

  # Messages settings for different events
  messages:
    onSpawn:
      actionbar: true
      title: true
      chat: true
    onCollect:
      actionbar: true
      title: true
      chat: true
    onTimer:
      actionbar: true

  # Title display duration
  title:
    fade-in: 10
    stay: 30
    fade-out: 10

  # Sounds for opening and closing the crate
  sounds:
    open:
      sound: NONE # NONE value will mute the sound, swap it with a sound from your server version.
      volume: 1.0
      pitch: 1.0
    close:
      sound: NONE
      volume: 1.0
      pitch: 1.0