name: PrtMineTreasures
version: ${version}
main: dev.pretti.prtminetreasures.PrtMineTreasures
author: Pretti_
api-version: 1.13
softdepend: [ "WorldGuard", "PlaceholderAPI", "Vault", "mcMMO" ]

commands:
  PrtMineTreasures:
    aliases: [ minetreasures, mt ]